name: Installing Python

on: [push]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: SuperPassword

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        py-version: [3.7, 3.8, 3.9]
        exclude:
          - os: macos-12
            py-version: 3.9   # Exclude macos-12 with Python 3.9

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}

    - name: Verify Python version
      run: python --version

    - name: Print environment variables (for debug)
      run: |
        echo $MONGO_URI
        echo $MONGO_USERNAME
        echo $MONGO_PASSWORD
